name: Preview Deploy

on:
  pull_request:
    types: [opened, synchronize]

env:
  PYTHON_VERSION: "3.11"

jobs:
  preview-test:
    name: Preview Test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        pytest

    - name: Build preview image
      run: |
        docker build -t preview-api .

    - name: Test preview image
      run: |
        docker run --rm -d --name preview -p 8000:8000 preview-api
        sleep 10
        curl -f http://localhost:8000/api/v1/health || exit 1
        docker stop preview

  comment-pr:
    name: Comment on PR
    runs-on: ubuntu-latest
    needs: preview-test
    if: github.event_name == 'pull_request'

    steps:
    - name: Comment PR
      uses: actions/github-script@v7
      with:
        script: |
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: `## 🚀 Preview Build Status

            ✅ **Tests passed**
            ✅ **Docker build successful**
            ✅ **Health check passed**

            This PR is ready for review and deployment!

            ---

            *Automated comment from CI/CD pipeline*`
          })